cron_schedule: '*/10 * * * *'
earliest_time: '-10m'
latest_time: 'now'
app: 'sigma_hunting_app'
type: 'report'
whitelist: 1
alert_action: 
    summary_index:
        source: 1
        name: 'threat-hunting'

