app: 'sigma_hunting_app'
cron_schedule: '*/10 * * * *'
earliest_time: '-10m'
latest_time: 'now'
schedule_window: auto
allow_skew: '50%'
search_transformations:
    - add_host_field
    - add_transforming_command
    - add_whitelist
alert_action:
    summary_index:
        name: 'threat-hunting'
        enrich_tags: 1
        enrich_level: 1
